package com.chap01.runtimeException;

import java.util.Scanner;

public class RunException {	
	Scanner sc = new Scanner(System.in);
	
	public static void main(String[] args) {
		
		//re.arithEx();
		//re.classAndArrayAndNullEx();
	}
	
	//ArithmeticException인 경우
	public void arithEx() {
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
	}
	
	public void classAndArrayAndNullEx() {
		//ClassCaseException
		/*Object obj = 'a';
		System.out.println(obj);
		String str = (String)obj;
		System.out.println(str.length());*/
		
		//ArrayIndexOutOfBoundsException
		/*int[] arr = new int[2];
		arr[0] = 1;
		arr[1] = 2;
		
		arr[2] = 3;
		System.out.println("출력문!!");*/
		
		//NullPointerException
		String str = null;
		str.length();
		
		
	}
	

	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

}
